# Generated by Django 5.1.3 on 2024-11-06 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_loan_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 20, 23, 29, 45, 399691, tzinfo=datetime.timezone.utc)),
        ),
    ]
