# Generated by Django 5.1.3 on 2024-11-06 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_loan_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 20, 23, 32, 57, 667129, tzinfo=datetime.timezone.utc)),
        ),
    ]
