# Generated by Django 5.1.3 on 2024-11-06 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_loan_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 20, 23, 58, 56, 476743, tzinfo=datetime.timezone.utc)),
        ),
    ]
