# Generated by Django 5.1.3 on 2024-11-07 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_loan_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 0, 8, 13, 364832, tzinfo=datetime.timezone.utc)),
        ),
    ]
